version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-with-pdf
    post_build:
          - mkdir -p $READTHEDOCS_OUTPUT/pdf/
          - mkdocs build
          - ls -lR
          - mv ./site/builds.pdf $READTHEDOCS_OUTPUT/pdf/
          - ls $READTHEDOCS_OUTPUT/pdf/
mkdocs:
  configuration: mkdocs.yaml

formats:
  - pdf