version: "2"

build:
  os: "ubuntu-24.04"
  tools:
    python: "3"
  jobs:
    pre_install:
      - pip install mkdocs-with-pdf
    post_build:
      - pwd
      - mkdir -pv $READTHEDOCS_OUTPUT/pdf/
      - tree
      - mv ./site/builds.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf
      - ls $READTHEDOCS_OUTPUT/pdf/
mkdocs:
  configuration: mkdocs.yaml

formats:
  - pdf