"""
This simple script populates specification.md with markdown tables generated by
schema2md.py
"""

from schema2md import schema2md

# Open the specification template
with open("templates/specification.template", "r") as f:
    specification_template = f.read()

# Load the global and variable attribute tables from the schema
SCHEMA_URL = "https://raw.githubusercontent.com/ACCESS-NRI/schema/refs/heads/main/au.org.access-nri/model/output/file-metadata/2-0-0/2-0-0.json"
global_table, variable_table = schema2md(SCHEMA_URL)
d = {
    "global_attrs_table": global_table,
    "variable_attrs_table": variable_table,
}

# Put the tables into the template and output to file
with open("docs/specification.md", "w") as output_f:
    output_f.write(specification_template.format(**d))
