"""
This simple script populates the README with markdown tables generated by
schema2md.py
"""

from schema2md import schema2md

# Open the readme template
with open("docs/README.template", "r") as f:
    readme_template = f.read()

# Open the global and variable tables
SCHEMA_URL = "https://raw.githubusercontent.com/ACCESS-NRI/schema/refs/heads/main/au.org.access-nri/model/output/file-metadata/2-0-0/2-0-0.json"
global_table, variable_table = schema2md(SCHEMA_URL)
d = {
    "global_attrs_table": global_table,
    "variable_attrs_table": variable_table,
}

with open("README.md", "w") as output_f:
    output_f.write(readme_template.format(**d))
