"""
This simple script populates the README with markdown tables generated by
schema2md.py
"""

from schema2md import mapping2md

# Open the mapping template
with open("templates/mapping.template", "r") as f:
    mapping_template = f.read()

# Open the global and variable tables
mapping_table = mapping2md()
d = {
    "mapping_table": mapping_table,
}

with open("docs/mapping.md", "w") as output_f:
    output_f.write(mapping_template.format(**d))
